Importing libraries

In [ ]:
#Importing all necessary libraries
import pandas as pd     #Importing pandas library for dataframe
import numpy as np      #Importing numpy library for arrays
import matplotlib.pyplot as plt     #Importing matplotlib library for visualization
import seaborn as sns       #Importing library for visualization
from sklearn.preprocessing import LabelEncoder     #Importing sklearn.preprocessing for encoding target label
from sklearn.preprocessing import StandardScaler     #Importing sklearn.prepocessing for normalization
from sklearn.model_selection import train_test_split    #Importing sklearn.model_selection for splitting train_test data
from sklearn.impute import SimpleImputer     #Importing sklearn.impute for filling Nan values
from sklearn.feature_selection import VarianceThreshold     #Importing sklearn.feature_selection for feature selection
from sklearn.ensemble import RandomForestRegressor     #Importing sklearn.ensemble for random forest regressor
from sklearn.model_selection import GridSearchCV     #Importing sklearn.model_selection for grid search
from sklearn.linear_model import LinearRegression     #Importing sklearn.linear_model for linear regression
from sklearn.feature_selection import RFE     #Importing sklearn.feature_selection for feature selection
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score     #Importing sklearn.metrics for confusion matrix and accuracy score
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error     #Importing sklearn.metrics for mean squared error and r2 score
import pickle     #Importing pickle for saving model
import joblib     #Importing joblib for saving model

In [ ]:
#Importing drive from google colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Importing table from drive
vd = pd.read_excel('/content/drive/MyDrive/Software System Engineering/Coursework/kaggle_london_house_price_data..xlsx')

In [ ]:
#Show table
vd.head()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_lowerPrice,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,570000.0,600000.0,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,540000.0,600000.0,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,683000.0,759000.0,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,368000.0,388000.0,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1198000.0,1261000.0,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,133000,NaN,NaN

In [ ]:
#Table information   - to check for null values
vd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418201 entries, 0 to 418200
Data columns (total 26 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                418201 non-null  object
 1   postcode                                   418201 non-null  object
 2   country                                    418201 non-null  object
 3   outcode                                    418201 non-null  object
 4   latitude                                   418201 non-null  float64
 5   longitude                                  418201 non-null  float64
 6   bathrooms                                  340270 non-null  float64
 7   bedrooms                                   377665 non-null  float64
 8   floorAreaSqM                               392991 non-null  float64
 9   livingRooms                                357701 non-null  float64
 10  tenure                                     406689 non-null  object
 11  propertyType                               417065 non-null  object
 12  currentEnergyRating                        333675 non-null  object
 13  rentEstimate_lowerPrice                    416460 non-null  float64
 14  rentEstimate_currentPrice                  416460 non-null  float64
 15  rentEstimate_upperPrice                    416460 non-null  float64
 16  saleEstimate_lowerPrice                    417561 non-null  float64
 17  saleEstimate_currentPrice                  417561 non-null  float64
 18  saleEstimate_upperPrice                    417561 non-null  float64
 19  saleEstimate_confidenceLevel               417561 non-null  object
 20  saleEstimate_ingestedAt                    417561 non-null  object
 21  saleEstimate_valueChange.numericChange     417561 non-null  float64
 22  saleEstimate_valueChange.percentageChange  417561 non-null  float64
 23  history_price                              418201 non-null  object
 24  history_percentageChange                   237982 non-null  float64
 25  history_numericChange                      237982 non-null  float64
dtypes: float64(16), object(10)
memory usage: 83.0+ MB

In [ ]:
vd.columns

Index(['fullAddress', 'postcode', 'country', 'outcode', 'latitude',
       'longitude', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms',
       'tenure', 'propertyType', 'currentEnergyRating',
       'rentEstimate_lowerPrice', 'rentEstimate_currentPrice',
       'rentEstimate_upperPrice', 'saleEstimate_lowerPrice',
       'saleEstimate_currentPrice', 'saleEstimate_upperPrice',
       'saleEstimate_confidenceLevel', 'saleEstimate_ingestedAt',
       'saleEstimate_valueChange.numericChange',
       'saleEstimate_valueChange.percentageChange', 'history_price',
       'history_percentageChange', 'history_numericChange'],
      dtype='object')

In [ ]:
#Checking for numeric columns with symbols
for col in vd.select_dtypes(include=['number']):
    print(col, vd[col].astype(str).str.contains(r'[^0-9.\-]').any())

latitude False
longitude True
bathrooms True
bedrooms True
floorAreaSqM True
livingRooms True
rentEstimate_lowerPrice True
rentEstimate_currentPrice True
rentEstimate_upperPrice True
saleEstimate_lowerPrice True
saleEstimate_currentPrice True
saleEstimate_upperPrice True
saleEstimate_valueChange.numericChange True
saleEstimate_valueChange.percentageChange True
history_percentageChange True
history_numericChange True

In [ ]:
#Checking for missing values
vd.isnull()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_lowerPrice,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,history_price,history_percentageChange,history_numericChange
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418196,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
418197,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
418198,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
418199,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
418200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
imputer = SimpleImputer(strategy='mean')

# Identify numeric columns with missing values
numeric_cols_with_nan = vd.select_dtypes(include=np.number).columns[vd.select_dtypes(include=np.number).isnull().any()].tolist()

# Apply imputer only to these numeric columns
vd[numeric_cols_with_nan] = imputer.fit_transform(vd[numeric_cols_with_nan])

In [ ]:
vd['saleEstimate_confidenceLevel'] = vd['saleEstimate_confidenceLevel'].fillna('Unknown')

In [ ]:
vd['saleEstimate_confidenceLevel'].unique()

array(['HIGH', 'MEDIUM', 'LOW', 'Unknown'], dtype=object)

In [ ]:
#Preparing target label: to ensure saleEstimate_confidenceLevel is treated as a numerical label and not a continous value
le = LabelEncoder()
vd['saleEstimate_confidenceLevel'] = le.fit_transform(vd['saleEstimate_confidenceLevel'])

list(zip(le.classes_, le.transform(le.classes_)))

[('HIGH', np.int64(0)),
 ('LOW', np.int64(1)),
 ('MEDIUM', np.int64(2)),
 ('Unknown', np.int64(3))]

In [ ]:
vd['propertyType'] = vd['propertyType'].fillna('Unknown')

In [ ]:
#Preparing target label: to ensure propertyType is treated as a numerical label and not a continous value
le = LabelEncoder()
vd['propertyType'] = le.fit_transform(vd['propertyType'])

list(zip(le.classes_, le.transform(le.classes_)))

[('Bungalow Property', np.int64(0)),
 ('Converted Flat', np.int64(1)),
 ('Detached Bungalow', np.int64(2)),
 ('Detached House', np.int64(3)),
 ('Detached Property', np.int64(4)),
 ('End Terrace Bungalow', np.int64(5)),
 ('End Terrace House', np.int64(6)),
 ('End Terrace Property', np.int64(7)),
 ('Flat/Maisonette', np.int64(8)),
 ('Mid Terrace Bungalow', np.int64(9)),
 ('Mid Terrace House', np.int64(10)),
 ('Mid Terrace Property', np.int64(11)),
 ('Purpose Built Flat', np.int64(12)),
 ('Semi-Detached Bungalow', np.int64(13)),
 ('Semi-Detached House', np.int64(14)),
 ('Semi-Detached Property', np.int64(15)),
 ('Terrace Property', np.int64(16)),
 ('Terraced', np.int64(17)),
 ('Terraced Bungalow', np.int64(18)),
 ('Unknown', np.int64(19))]

In [ ]:
vd['tenure'] = vd['tenure'].fillna('Unknown')

In [ ]:
#Preparing target label: to ensure tenure is treated as a numerical label and not a continous value
le = LabelEncoder()
vd['tenure'] = le.fit_transform(vd['tenure'])

list(zip(le.classes_, le.transform(le.classes_)))

[('Feudal', np.int64(0)),
 ('Freehold', np.int64(1)),
 ('Leasehold', np.int64(2)),
 ('Shared', np.int64(3)),
 ('Unknown', np.int64(4))]

In [ ]:
vd['currentEnergyRating'] = vd['currentEnergyRating'].fillna('Unknown')

In [ ]:
#Preparing target label: to ensure currentEnergyRating is treated as a numerical label and not a continous value
le = LabelEncoder()
vd['currentEnergyRating'] = le.fit_transform(vd['currentEnergyRating'])

list(zip(le.classes_, le.transform(le.classes_)))

[('A', np.int64(0)),
 ('B', np.int64(1)),
 ('C', np.int64(2)),
 ('D', np.int64(3)),
 ('E', np.int64(4)),
 ('F', np.int64(5)),
 ('G', np.int64(6)),
 ('Unknown', np.int64(7))]

In [45]:
# Dropping target column and other non-numeric columns
non_numeric_cols = [
    'fullAddress',
    'postcode',
    'country',
    'outcode',
    'saleEstimate_ingestedAt',
    'history_price',
    'saleEstimate_currentPrice' # Target column
]
X = vd.drop(columns=non_numeric_cols, axis=1)
y = vd['saleEstimate_currentPrice']

# Training a temporary Random Forest model

temp_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

temp_model.fit(X, y)

# Create feature importance table
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': temp_model.feature_importances_
})

# Show most important features first
importance = importance.sort_values(by='Importance', ascending=False)

print(importance)

                                      Feature    Importance
13                    saleEstimate_upperPrice  9.800248e-01
12                    saleEstimate_lowerPrice  1.907400e-02
11                    rentEstimate_upperPrice  4.165610e-04
9                     rentEstimate_lowerPrice  2.479048e-04
10                  rentEstimate_currentPrice  1.714140e-04
0                                    latitude  1.503024e-05
1                                   longitude  1.380882e-05
7                                propertyType  1.170999e-05
15     saleEstimate_valueChange.numericChange  6.694692e-06
14               saleEstimate_confidenceLevel  5.579334e-06
16  saleEstimate_valueChange.percentageChange  3.327358e-06
17                   history_percentageChange  2.071498e-06
4                                floorAreaSqM  1.917076e-06
3                                    bedrooms  1.099360e-06
8                         currentEnergyRating  1.030835e-06
18                      history_numericChange  9.057181e-07
5                                 livingRooms  8.513073e-07
6                                      tenure  7.036319e-07
2                                   bathrooms  5.776511e-07

Machine Learning

In [46]:
#Definning x and y values
X = vd[['bedrooms', 'floorAreaSqM', 'propertyType', 'rentEstimate_upperPrice', 'bathrooms', 'livingRooms', 'tenure', 'currentEnergyRating']]
y = vd['saleEstimate_currentPrice'].values

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [48]:
#shape of train and test data for EMPA dataset
X_train.shape, X_test.shape

((334560, 8), (83641, 8))

In [49]:
#Normalization/scalling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [50]:
# Linear Regressor - Create model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [51]:
lr_pred = lr.predict(X_test)

mae = mean_absolute_error(y_test, lr_pred)
mse = mean_squared_error(y_test, lr_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, lr_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)
print("MSE:", mse)

MAE: 86573.03557263629
RMSE: 168094.42710149748
R²: 0.9669042200000593
MSE: 28255736422.580654

In [52]:
# Define the full path
file_path = r"/content/drive/MyDrive/Software System Engineering/Coursework/Models/linear_regression_model.pkl"

# Save the model
with open(file_path, 'wb') as file:
    pickle.dump(lr, file)

print("Model saved successfully.")
print("Saved to:", file_path)

Model saved successfully.
Saved to: /content/drive/MyDrive/Software System Engineering/Coursework/Models/linear_regression_model.pkl

In [53]:
# RandonForestRegressor - Create model
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [54]:
# Make predictions
y_pred = model.predict(X_test)
print(y_pred)

[1204900.          597744.73914974  705830.         ...  513060.
 1279130.         1174820.        ]

In [55]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)
print("MSE:", mse)

MAE: 39420.10690853463
RMSE: 104388.7589699593
R²: 0.9669042200000593
MSE: 10897012999.288256

In [56]:
# Define the full path
file_path = r"/content/drive/MyDrive/Software System Engineering/Coursework/Models/random_forest_model.pkl"

# Save the trained Random Forest model
with open(file_path, 'wb') as file:
    pickle.dump(model, file)

print("Model saved successfully.")
print("Saved to:", file_path)

Model saved successfully.
Saved to: /content/drive/MyDrive/Software System Engineering/Coursework/Models/random_forest_model.pkl

In [57]:
print("Predicted:", y_pred[:10])
print("Actual:   ", y_test[:10])

Predicted: [1204900.          597744.73914974  705830.          734365.5952381
  677010.          571791.21212121  277109.66376667  697179.34965063
  869441.83333333 1071700.        ]
Actual:    [1169000.  624000.  710000.  619000.  675000.  550000.  256000.  687000.
  831000. 1063000.]

In [58]:
feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance)

rentEstimate_upperPrice    0.975891
floorAreaSqM               0.009657
propertyType               0.003308
currentEnergyRating        0.002878
bedrooms                   0.002693
bathrooms                  0.002362
livingRooms                0.001985
tenure                     0.001225
dtype: float64

In [59]:
sample = X_test[0].reshape(1, -1)
prediction = model.predict(sample)

print("Prediction:", prediction)

Prediction: [1204900.]